// 1 级到神 40 成长倍数
const DAMGE_VALUE_RATIO = 3.63

// +12 勋章攻强
const DAMGE_VALUE_MEDAL = 25423

// 总攻强
const DAMAGE_VALUE_ALL = 354924

// 贴膜攻强（左灵通2+猎食3，右孤岛3+监视者3）
const DAMAGE_VALUE_FUSION = 3756 + 7034 + 6213 + 4321 + 10830 * 3 + 3800 * 3

// 装备攻强（出血散搭9自定义）
const DAMGE_VALUE_EQUIPMENTS = DAMAGE_VALUE_ALL - DAMAGE_VALUE_FUSION - DAMGE_VALUE_MEDAL

// 用于装备横向对比的攻强
export const DAMAGE_VALUE_EQUIPMENT_COMPARATION = Math.round(
  (DAMGE_VALUE_EQUIPMENTS / DAMGE_VALUE_RATIO) * (11 / 12) +
    DAMAGE_VALUE_FUSION / DAMGE_VALUE_RATIO,
)

// 用于贴膜横向对比的攻强
export const DAMAGE_VALUE_FUSION_COMPARATION = Math.round(
  DAMAGE_VALUE_ALL - DAMAGE_VALUE_FUSION / 11,
)

// 模板属强
export const ELEMENTAL_DAMAGE = 436

// 灼烧破冰率
export const BURN_BREAK_ICE_RATE = 75
